/**
 * Created by qi on 2016/12/1.
 */

//违禁词相关常量
const PROHIBITED_WORD_POLITICAL = 1;
const PROHIBITED_WORD_LAWLESS = 2;
const PROHIBITED_WORD_OBSCENE = 3;
const PROHIBITED_WORD_SPAM = 4;
const PROHIBITED_GRADE_ONE = 1;
const PROHIBITED_GRADE_TWO = 2;
const PROHIBITED_GRADE_THREE = 3;
const PROHIBITED_WORD_ENABLE = 1;
const PROHIBITED_WORD_DISABLE = 0;

//违禁词审核相关常量
const PROHIBITED_SOURCE_NICK = 1;
const PROHIBITED_SOURCE_SIGNATURE = 2;
const PROHIBITED_SOURCE_OGCARTICLE = 3;
const PROHIBITED_SOURCE_UGCCOMMENT = 4;
const PROHIBITED_SOURCE_CRAWLER = 5;
const ARTIFICIAL_AUDIT_WAIT = 0;
const ARTIFICIAL_AUDIT_PASS = 1;
const ARTIFICIAL_AUDIT_REFUSE = 2;
const MACHINE_AUDIT_PASS = 1;
const MACHINE_AUDIT_REFUSE = 0;
const TO_ARTIFICIAL_AUDIT = 1;
const NO_ARTIFICIAL_AUDIT = 0;

//违禁词库常量
const PROHIBITED_LEXICON_NICK = 1;
const PROHIBITED_LEXICON_UGC = 2;
const PROHIBITED_LEXICON_CRAWLER = 3;

//result 状态常量
const RESPONSE_AUDIT_REFUSE = 0;
const RESPONSE_AUDIT_PASS = 1;
const RESPONSE_AUDIT_REFUSE_HIGHEST = 2;

//redis key
const ACTREE_UPDATE_TIME_CACHE_KEY = '_ACTree:time';

export {

    PROHIBITED_WORD_POLITICAL,
    PROHIBITED_WORD_LAWLESS,
    PROHIBITED_WORD_OBSCENE,
    PROHIBITED_WORD_SPAM,
    PROHIBITED_GRADE_ONE,
    PROHIBITED_GRADE_TWO,
    PROHIBITED_GRADE_THREE,
    PROHIBITED_WORD_ENABLE,
    PROHIBITED_WORD_DISABLE,
    PROHIBITED_SOURCE_NICK,
    PROHIBITED_SOURCE_SIGNATURE,
    PROHIBITED_SOURCE_OGCARTICLE,
    PROHIBITED_SOURCE_UGCCOMMENT,
    PROHIBITED_SOURCE_CRAWLER,
    PROHIBITED_LEXICON_NICK,
    PROHIBITED_LEXICON_UGC,
    PROHIBITED_LEXICON_CRAWLER,
    ARTIFICIAL_AUDIT_WAIT,
    ARTIFICIAL_AUDIT_PASS,
    ARTIFICIAL_AUDIT_REFUSE,
    MACHINE_AUDIT_PASS,
    MACHINE_AUDIT_REFUSE,
    TO_ARTIFICIAL_AUDIT,
    NO_ARTIFICIAL_AUDIT,
    RESPONSE_AUDIT_REFUSE,
    RESPONSE_AUDIT_PASS,
    RESPONSE_AUDIT_REFUSE_HIGHEST,
    ACTREE_UPDATE_TIME_CACHE_KEY
};